# ekf.yaml
ekf_node:
  ros__parameters:
    frequency: 30.0                 # EKF update frequency
    sensor_timeout: 0.5             # tolerate slower IMU
    two_d_mode: false                # set true if you operate on planar robots
    publish_tf: false
    publish_acceleration: false
    map_frame: utm
    odom_frame: utm
    world_frame: odom              
    base_link_frame: base_link
    print_diagnostics: true
    debug: true
    debug_out_file: src/osm_align/ekf.log
    # odom_topic: /ekf/odom   # ← your custom topic name
    # ------------ ODOM INPUT ------------
    odom0: /kitti/gtruth/odom   
    # odom0: /liodom/odom
    # odom0: /osm_align/odom
    odom0_relative: false #Absolute pose
    odom0_differential: false
    # Which odom fields to fuse (pose x,y,yaw and twist vx, vyaw)
    odom0_config: [true,  true,  true, #Pose X,Y, Z, 
                   true, true, true, # roll,  pitch,yaw,
                   false, false, false, # X_velocity,Y_velocity,Z_velocity,
                   false, false, false, # roll_velocity,pitch_velocity,yaw_velocity,
                   false, false, false] # X_acceleration,Y_acceleration,Z_acceleration


    # odom1: /liodom/odom            # or /odom if that's your topic
    ododm1:  /osm_align/odom
    odom1_relative: false #Absolute pose
    odom1_differential: true
    # Which odom fields to fuse (pose x,y,yaw and twist vx, vyaw)
    odom1_config: [true,  true,  true, #Pose X,Y, Z, 
                   true, true, true, # roll, pitch,yaw,
                   false, false, false, # X_velocity,Y_velocity,Z_velocity,
                   false, false, false, # roll_velocity,pitch_velocity,yaw_velocity,
                   false, false, false] # X_acceleration,Y_acceleration,Z_acceleration
    # ------------ IMU INPUT -------------
    # imu0: /kitti/oxts/imu
    # imu0_relative: false
    # imu0_config: [false, false, false,
    #               false, false, false,     
    #               false, false, false,
    #               false, false, true,     
    #               true,  true,  false]  

